#!/usr/bin/perl -w
# do-author-title-note
# finish converting entries having 3 lines each: author(s) \n title \n note

$cite0 = '@c';
$cite1 = 'ct-16 . . 2016';

$home = $ENV{HOME};
$bib = $home . '/l/src/script/bib/';
require $bib . '/tolower.pl';
require $bib . '/author.pl';
require $bib . '/bibkey.pl';

$/ = ""; # slurp paragraph at time

while (<STDIN>)
{
	if (/^#/) # echo comments
	{
		print "$_\n";
		next;
	}

	@all = split(/\n/);
	$nline = $#all + 1;

	die "bad paragraph ($nline):\n`$_'\n" unless ($nline == 3);

	$authors = $all[0];
	$title = $all[1];
	$note = $all[2];

	$authors = &author($authors);
	$title = &TitleLower($title);

	$fake = "$cite0 xx:xx:xx $cite1\n$authors\n$title\n";
	@bibkey = &bibkey($fake); 
	($author, $year, $code) = @bibkey;
	die "code" unless defined($code);
	$key = "$author:$year:$code";

	$cite = $cite1;

	print "$cite0 $key $cite\n";
	print "$authors\n$title\n";
	print "\@an $note\n";
	print "\n";
}
