#!/usr/bin/perl -w
# xplore,url
# called within xplore,to,b2 to extract concise url from long ieee url

while (<STDIN>) {
	if (/\[Abstract\]/) {
		($num) = /isNumber=(\d*)/;
		($art) = /arnumber=(\d*)/;
		print "\@u ieee $num $art\n";
	} else {
		print "$_";
	}
}
