#!/bin/csh
#	do [files]
#	change to new definitions

foreach file ($*)
	echo $file
	set new = $file.new
	sed < $file > $new -f ~/tex/biblio/script/j.sed
	if $status then
		echo sed failed
		exit
	endif

	diff $file $new > /dev/null
	if $status then
		mv $file $file.old.$$
		mv $new $file
		echo changed $file
	else
		echo no change to $file
	endif
	rm -f $new
end
